/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObjectivesRouteImport } from './routes/objectives'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerIdRouteImport } from './routes/player.$id'
import { Route as PlayerIdTokensRouteImport } from './routes/player.$id.tokens'
import { Route as PlayerIdScoreRouteImport } from './routes/player.$id.score'
import { Route as PlayerIdScanRouteImport } from './routes/player.$id.scan'
import { Route as PlayerIdRulesRouteImport } from './routes/player.$id.rules'
import { Route as PlayerIdReviewRouteImport } from './routes/player.$id.review'
import { Route as PlayerIdObjectiveRouteImport } from './routes/player.$id.objective'

const ObjectivesRoute = ObjectivesRouteImport.update({
  id: '/objectives',
  path: '/objectives',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIdRoute = PlayerIdRouteImport.update({
  id: '/player/$id',
  path: '/player/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIdTokensRoute = PlayerIdTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => PlayerIdRoute,
} as any)
const PlayerIdScoreRoute = PlayerIdScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => PlayerIdRoute,
} as any)
const PlayerIdScanRoute = PlayerIdScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => PlayerIdRoute,
} as any)
const PlayerIdRulesRoute = PlayerIdRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => PlayerIdRoute,
} as any)
const PlayerIdReviewRoute = PlayerIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => PlayerIdRoute,
} as any)
const PlayerIdObjectiveRoute = PlayerIdObjectiveRouteImport.update({
  id: '/objective',
  path: '/objective',
  getParentRoute: () => PlayerIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/objectives': typeof ObjectivesRoute
  '/player/$id': typeof PlayerIdRouteWithChildren
  '/player/$id/objective': typeof PlayerIdObjectiveRoute
  '/player/$id/review': typeof PlayerIdReviewRoute
  '/player/$id/rules': typeof PlayerIdRulesRoute
  '/player/$id/scan': typeof PlayerIdScanRoute
  '/player/$id/score': typeof PlayerIdScoreRoute
  '/player/$id/tokens': typeof PlayerIdTokensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/objectives': typeof ObjectivesRoute
  '/player/$id': typeof PlayerIdRouteWithChildren
  '/player/$id/objective': typeof PlayerIdObjectiveRoute
  '/player/$id/review': typeof PlayerIdReviewRoute
  '/player/$id/rules': typeof PlayerIdRulesRoute
  '/player/$id/scan': typeof PlayerIdScanRoute
  '/player/$id/score': typeof PlayerIdScoreRoute
  '/player/$id/tokens': typeof PlayerIdTokensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/objectives': typeof ObjectivesRoute
  '/player/$id': typeof PlayerIdRouteWithChildren
  '/player/$id/objective': typeof PlayerIdObjectiveRoute
  '/player/$id/review': typeof PlayerIdReviewRoute
  '/player/$id/rules': typeof PlayerIdRulesRoute
  '/player/$id/scan': typeof PlayerIdScanRoute
  '/player/$id/score': typeof PlayerIdScoreRoute
  '/player/$id/tokens': typeof PlayerIdTokensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/objectives'
    | '/player/$id'
    | '/player/$id/objective'
    | '/player/$id/review'
    | '/player/$id/rules'
    | '/player/$id/scan'
    | '/player/$id/score'
    | '/player/$id/tokens'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/objectives'
    | '/player/$id'
    | '/player/$id/objective'
    | '/player/$id/review'
    | '/player/$id/rules'
    | '/player/$id/scan'
    | '/player/$id/score'
    | '/player/$id/tokens'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/objectives'
    | '/player/$id'
    | '/player/$id/objective'
    | '/player/$id/review'
    | '/player/$id/rules'
    | '/player/$id/scan'
    | '/player/$id/score'
    | '/player/$id/tokens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ObjectivesRoute: typeof ObjectivesRoute
  PlayerIdRoute: typeof PlayerIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/objectives': {
      id: '/objectives'
      path: '/objectives'
      fullPath: '/objectives'
      preLoaderRoute: typeof ObjectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$id': {
      id: '/player/$id'
      path: '/player/$id'
      fullPath: '/player/$id'
      preLoaderRoute: typeof PlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$id/tokens': {
      id: '/player/$id/tokens'
      path: '/tokens'
      fullPath: '/player/$id/tokens'
      preLoaderRoute: typeof PlayerIdTokensRouteImport
      parentRoute: typeof PlayerIdRoute
    }
    '/player/$id/score': {
      id: '/player/$id/score'
      path: '/score'
      fullPath: '/player/$id/score'
      preLoaderRoute: typeof PlayerIdScoreRouteImport
      parentRoute: typeof PlayerIdRoute
    }
    '/player/$id/scan': {
      id: '/player/$id/scan'
      path: '/scan'
      fullPath: '/player/$id/scan'
      preLoaderRoute: typeof PlayerIdScanRouteImport
      parentRoute: typeof PlayerIdRoute
    }
    '/player/$id/rules': {
      id: '/player/$id/rules'
      path: '/rules'
      fullPath: '/player/$id/rules'
      preLoaderRoute: typeof PlayerIdRulesRouteImport
      parentRoute: typeof PlayerIdRoute
    }
    '/player/$id/review': {
      id: '/player/$id/review'
      path: '/review'
      fullPath: '/player/$id/review'
      preLoaderRoute: typeof PlayerIdReviewRouteImport
      parentRoute: typeof PlayerIdRoute
    }
    '/player/$id/objective': {
      id: '/player/$id/objective'
      path: '/objective'
      fullPath: '/player/$id/objective'
      preLoaderRoute: typeof PlayerIdObjectiveRouteImport
      parentRoute: typeof PlayerIdRoute
    }
  }
}

interface PlayerIdRouteChildren {
  PlayerIdObjectiveRoute: typeof PlayerIdObjectiveRoute
  PlayerIdReviewRoute: typeof PlayerIdReviewRoute
  PlayerIdRulesRoute: typeof PlayerIdRulesRoute
  PlayerIdScanRoute: typeof PlayerIdScanRoute
  PlayerIdScoreRoute: typeof PlayerIdScoreRoute
  PlayerIdTokensRoute: typeof PlayerIdTokensRoute
}

const PlayerIdRouteChildren: PlayerIdRouteChildren = {
  PlayerIdObjectiveRoute: PlayerIdObjectiveRoute,
  PlayerIdReviewRoute: PlayerIdReviewRoute,
  PlayerIdRulesRoute: PlayerIdRulesRoute,
  PlayerIdScanRoute: PlayerIdScanRoute,
  PlayerIdScoreRoute: PlayerIdScoreRoute,
  PlayerIdTokensRoute: PlayerIdTokensRoute,
}

const PlayerIdRouteWithChildren = PlayerIdRoute._addFileChildren(
  PlayerIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  ObjectivesRoute: ObjectivesRoute,
  PlayerIdRoute: PlayerIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
