/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObjectivesRouteImport } from './routes/objectives'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerIdTokensRouteImport } from './routes/player.$id.tokens'
import { Route as PlayerIdScoreRouteImport } from './routes/player.$id.score'
import { Route as PlayerIdScanRouteImport } from './routes/player.$id.scan'
import { Route as PlayerIdReviewRouteImport } from './routes/player.$id.review'
import { Route as PlayerIdObjectiveRouteImport } from './routes/player.$id.objective'

const ObjectivesRoute = ObjectivesRouteImport.update({
  id: '/objectives',
  path: '/objectives',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIdTokensRoute = PlayerIdTokensRouteImport.update({
  id: '/player/$id/tokens',
  path: '/player/$id/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIdScoreRoute = PlayerIdScoreRouteImport.update({
  id: '/player/$id/score',
  path: '/player/$id/score',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIdScanRoute = PlayerIdScanRouteImport.update({
  id: '/player/$id/scan',
  path: '/player/$id/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIdReviewRoute = PlayerIdReviewRouteImport.update({
  id: '/player/$id/review',
  path: '/player/$id/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIdObjectiveRoute = PlayerIdObjectiveRouteImport.update({
  id: '/player/$id/objective',
  path: '/player/$id/objective',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/leaderboard': typeof LeaderboardRoute
  '/objectives': typeof ObjectivesRoute
  '/player/$id/objective': typeof PlayerIdObjectiveRoute
  '/player/$id/review': typeof PlayerIdReviewRoute
  '/player/$id/scan': typeof PlayerIdScanRoute
  '/player/$id/score': typeof PlayerIdScoreRoute
  '/player/$id/tokens': typeof PlayerIdTokensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/leaderboard': typeof LeaderboardRoute
  '/objectives': typeof ObjectivesRoute
  '/player/$id/objective': typeof PlayerIdObjectiveRoute
  '/player/$id/review': typeof PlayerIdReviewRoute
  '/player/$id/scan': typeof PlayerIdScanRoute
  '/player/$id/score': typeof PlayerIdScoreRoute
  '/player/$id/tokens': typeof PlayerIdTokensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/leaderboard': typeof LeaderboardRoute
  '/objectives': typeof ObjectivesRoute
  '/player/$id/objective': typeof PlayerIdObjectiveRoute
  '/player/$id/review': typeof PlayerIdReviewRoute
  '/player/$id/scan': typeof PlayerIdScanRoute
  '/player/$id/score': typeof PlayerIdScoreRoute
  '/player/$id/tokens': typeof PlayerIdTokensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/leaderboard'
    | '/objectives'
    | '/player/$id/objective'
    | '/player/$id/review'
    | '/player/$id/scan'
    | '/player/$id/score'
    | '/player/$id/tokens'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/leaderboard'
    | '/objectives'
    | '/player/$id/objective'
    | '/player/$id/review'
    | '/player/$id/scan'
    | '/player/$id/score'
    | '/player/$id/tokens'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/leaderboard'
    | '/objectives'
    | '/player/$id/objective'
    | '/player/$id/review'
    | '/player/$id/scan'
    | '/player/$id/score'
    | '/player/$id/tokens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ObjectivesRoute: typeof ObjectivesRoute
  PlayerIdObjectiveRoute: typeof PlayerIdObjectiveRoute
  PlayerIdReviewRoute: typeof PlayerIdReviewRoute
  PlayerIdScanRoute: typeof PlayerIdScanRoute
  PlayerIdScoreRoute: typeof PlayerIdScoreRoute
  PlayerIdTokensRoute: typeof PlayerIdTokensRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/objectives': {
      id: '/objectives'
      path: '/objectives'
      fullPath: '/objectives'
      preLoaderRoute: typeof ObjectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$id/tokens': {
      id: '/player/$id/tokens'
      path: '/player/$id/tokens'
      fullPath: '/player/$id/tokens'
      preLoaderRoute: typeof PlayerIdTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$id/score': {
      id: '/player/$id/score'
      path: '/player/$id/score'
      fullPath: '/player/$id/score'
      preLoaderRoute: typeof PlayerIdScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$id/scan': {
      id: '/player/$id/scan'
      path: '/player/$id/scan'
      fullPath: '/player/$id/scan'
      preLoaderRoute: typeof PlayerIdScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$id/review': {
      id: '/player/$id/review'
      path: '/player/$id/review'
      fullPath: '/player/$id/review'
      preLoaderRoute: typeof PlayerIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$id/objective': {
      id: '/player/$id/objective'
      path: '/player/$id/objective'
      fullPath: '/player/$id/objective'
      preLoaderRoute: typeof PlayerIdObjectiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LeaderboardRoute: LeaderboardRoute,
  ObjectivesRoute: ObjectivesRoute,
  PlayerIdObjectiveRoute: PlayerIdObjectiveRoute,
  PlayerIdReviewRoute: PlayerIdReviewRoute,
  PlayerIdScanRoute: PlayerIdScanRoute,
  PlayerIdScoreRoute: PlayerIdScoreRoute,
  PlayerIdTokensRoute: PlayerIdTokensRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
